<?php

return [
  'credentials' => [
      'user'                => 'Langarita@blasterinformation.com',
      'tracking_id'         => 'langarita-20',
      'access_key_id'       => 'AKIAIMD44RBVZ4WJ5ZXQ',
      'secret_access_key'   => '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',
    //   'access_key_id'       => 'AKIAJBQBQ56MC3LTTVPQ',
    //   'secret_access_key'   => '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',
      'results_per_page'    => 20,
      ],
      'category' => [
            'All'                => 'Todo',
            'Appliances'         => 'Accesorios',
            'ArtsAndCrafts'      => 'Artes, manualidades y Costura',
            'Automotive'         => 'Automotor',
            'Baby'               => 'Bebes',
            'Beauty'             => 'Belleza',
            'Blended'            => 'Mezclado',
            'Books'              => 'Libros',
            'Collectibles'       => 'Coleccionables y Bellas Artes',
            'Electronics'        => 'Electrónica',
            'Fashion'            => 'Prendas de vestir, calzado y joyería',
            'FashionBaby'        => 'Bebes - Prendas de vestir...',
            'FashionBoys'        => 'Niños - Prendas de vestir...',
            'FashionGirls'       => 'Niñas - Prendas de vestir...',
            'FashionMen'         => 'Hombres - Prendas de vestir...',
            'FashionWomen'       => 'Mujeres - Prendas de vestir...',
            'HealthPersonalCare' => 'Cuidado Personal y Salud',
            'Handmade'           => 'Hecho a Mano',
            'HomeGarden'         => 'Hogar y Cocina',
            'Jewelry'            => 'Joyeria',
            'Kitchen'            => 'Cocina',
            'KindleStore'        => 'Kindle',
            'Industrial'         => 'Industrial y Científica',
            'LawnAndGarden'      => 'Césped y jardín',
            'Luggage'            => 'Equipaje y artículos de viaje',
            // 'Magazines'          => 'Revistas',
            'Miscellaneous'      => 'Varios',
            'MusicalInstruments' => 'Instrumentos musicales',
            'Music'              => 'CDs & Vinyl',
            'OfficeProducts'     => 'Productos de oficina',
            'OutdoorLiving'      => 'Aire Libre',
            'PCHardware'         => 'Computadoras',
            'PetSupplies'        => 'Mascotas',
            'Software'           => 'Software',
            'Shoes'              => 'Zapatos',
            'SportingGoods'      => 'Artículos deportivos',
            'Tools'              => 'Herramientas',
            'Toys'               => 'juguetes',
            'VideoGames'         => 'Videojuegos',
            'Watches'            => 'Relojes',
            'Wireless'           => 'Teléfonos móviles y accesorios',
          ],
      'category_browse_node' => [
            'Appliances'         => '2619526011',
            'ArtsAndCrafts'      => '2617942011',
            'Automotive'         => '15690151',
            'Baby'               => '165797011',
            'Beauty'             => '11055981',
            'Books'              => '1000',
            'Collectibles'       => '4991426011',
            'Electronics'        => '493964',
            'Fashion'            => '7141124011',
            'FashionBaby'        => '7147444011',
            'FashionBoys'        => '7147443011',
            'FashionGirls'       => '7147442011',
            'FashionMen'         => '7147441011',
            'FashionWomen'       => '7147440011',
            'HealthPersonalCare' => '3760931',
            'HomeGarden'         => '1063498',
            'KindleStore'        => '133141011',
            'Industrial'         => '16310161',
            'LawnAndGarden'      => '3238155011',
            'Luggage'            => '9479199011',
            // 'Magazines'          => '599872',
            'MusicalInstruments' => '11965861',
            'Music'              => '301668',
            'OfficeProducts'     => '1084128',
            'PCHardware'         => '541966',
            'PetSupplies'        => '2619534011',
            'Software'           => '409488',
            'SportingGoods'      => '3375301',
            'Tools'              => '468240',
            'Toys'               => '165795011',
            'VideoGames'         => '11846801',
            'Wireless'           => '2335753011',
          ],
  'sort' => [
      'price' => 'Menor precio',
      '-price' => 'Mayor precio',
      'salesrank' => 'Mas votado',
      '-releasedate' => 'Fecha de publicación',
      ],
  'condition' => [
      'New'           => 'Nuevo',
      'Used'          => 'Usado',
      'Collectible'   => 'Coleccionable',
      'Refurbished'   => 'Reformado',
      'all'           => 'Todo',
      ],
      'equivalences'         => [
                          '2619526011'            => [
                                'node'            => '0',
                                'name'            => 'Appliances',
                                'meli_equivalence'     => 'MCO1953',
                            ],
                            '4991425011'          => [
                                  'node'          => '0',
                                  'name'          => 'ArtsAndCrafts',
                                  'meli_equivalence'   => 'MCO1953',
                              ],
                              '2617942011'        => [
                                    'node'        => '0',
                                    'name'        => 'ArtsAndCrafts',
                                    'meli_equivalence' => 'MCO1953',
                                ],
                              '2617941011'        => [
                                    'node'        => '0',
                                    'name'        => 'ArtsAndCrafts',
                                    'meli_equivalence' => 'MCO1953',
                                ],
                          '15690151'              => [
                                'node'            => '0',
                                'name'            => 'Automotive',
                                'meli_equivalence'     => 'MCO1747',
                            ],
                            '15684181'            => [
                                  'node'          => '0',
                                  'name'          => 'Automotive',
                                  'meli_equivalence'   => 'MCO1747',
                              ],
                          '165797011'             => [
                                'node'            => '0',
                                'name'            => 'Baby',
                                'meli_equivalence'     => 'MCO1384',
                            ],
                            '165796011'           => [
                                  'node'          => '0',
                                  'name'          => 'Baby',
                                  'meli_equivalence'   => 'MCO1384',
                              ],
                          '11055981'              => [
                                'node'            => '0',
                                'name'            => 'Beauty',
                                'meli_equivalence'     => 'MCO1246',
                            ],
                          '283155'                => [
                                'node'            => '0',
                                'name'            => 'Books',
                                'meli_equivalence'     => 'MCO3025',
                            ],
                            '283155'              => [
                                  'node'          => '0',
                                  'name'          => 'Books',
                                  'meli_equivalence'   => 'MCO3025',
                              ],
                          '4991426011'            => [
                                'node'            => '0',
                                'name'            => 'Collectibles',
                                'meli_equivalence'     => 'MCO1798',
                            ],
                          '493964'                => [
                                'node'            => '0',
                                'name'            => 'Electronics',
                                'meli_equivalence'     => 'MCO1000',
                            ],
                            '172282'              => [
                                  'node'          => '0',
                                  'name'          => 'Electronics',
                                  'meli_equivalence'   => 'MCO1000',
                              ],
                          '7141124011'            => [
                                'node'            => '0',
                                'name'            => 'Fashion',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                            '7147441011'          => [
                                  'node'          => '0',
                                  'name'          => 'Fashion',
                                  'meli_equivalence'   => 'MCO1430',
                              ],
                          '7147444011'            => [
                                'node'            => '0',
                                'name'            => 'FashionBaby',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                          '7147443011'            => [
                                'node'            => '0',
                                'name'            => 'FashionBoys',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                            '7141123011'          => [
                                  'node'          => '0',
                                  'name'          => 'FashionBoys',
                                  'meli_equivalence'   => 'MCO1430',
                              ],
                          '7147442011'            => [
                                'node'            => '0',
                                'name'            => 'FashionGirls',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                          '7147441011'            => [
                                'node'            => '0',
                                'name'            => 'FashionMen',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                          '7147440011'            => [
                                'node'            => '0',
                                'name'            => 'FashionWomen',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                            '3760901'             => [
                                  'node'          => '0',
                                  'name'          => 'HealthPersonalCare',
                                  'meli_equivalence'   => 'MCO1246',
                              ],
                              '3760931'           => [
                                    'node'        => '0',
                                    'name'        => 'HealthPersonalCare',
                                    'meli_equivalence' => 'MCO1246',
                                ],
                            '3760911'             => [
                                  'node'          => '0',
                                  'name'          => 'HealthPersonalCare',
                                  'meli_equivalence'   => 'MCO1246',
                              ],
                            '1063498'             => [
                                  'node'          => '0',
                                  'name'          => 'HomeGarden',
                                  'meli_equivalence'   => 'MCO1574',
                              ],
                              '1055398'           => [
                                    'node'        => '0',
                                    'name'        => 'HomeGarden',
                                    'meli_equivalence' => 'MCO1574',
                                ],
                          '133141011'             => [
                                'node'            => '0',
                                'name'            => 'KindleStore',
                                'meli_equivalence'     => '',
                            ],
                          '16310161'              => [
                                'node'            => '0',
                                'name'            => 'Industrial',
                                'meli_equivalence'     => 'MCO1499',
                            ],
                          '3238155011'            => [
                                'node'            => '0',
                                'name'            => 'LawnAndGarden',
                                'meli_equivalence'     => 'MCO1574',
                            ],
                          '9479199011'            => [
                                'node'            => '0',
                                'name'            => 'Luggage',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                          '599872'                => [
                                'node'            => '0',
                                'name'            => 'Magazines',
                                'meli_equivalence'     => 'MCO3025',
                            ],
                          '11965861'              => [
                                'node'            => '0',
                                'name'            => 'MusicalInstruments',
                                'meli_equivalence'     => 'MCO1182',
                            ],
                          '301668'                => [
                                'node'            => '0',
                                'name'            => 'Music',
                                'meli_equivalence'     => 'MCO1168',
                            ],
                          '1084128'               => [
                                'node'            => '0',
                                'name'            => 'OfficeProducts',
                                'meli_equivalence'     => 'MCO1953',
                            ],
                          '541966'                => [
                                'node'            => '0',
                                'name'            => 'PCHardware',
                                'meli_equivalence'     => 'MCO1648',
                            ],
                          '2619534011'            => [
                                'node'            => '0',
                                'name'            => 'PetSupplies',
                                'meli_equivalence'     => 'MCO1071',
                            ],
                          '409488'                => [
                                'node'            => '0',
                                'name'            => 'Software',
                                'meli_equivalence'     => 'MCO1648',
                            ],
                          '3375301'               => [
                                'node'            => '0',
                                'name'            => 'SportingGoods',
                                'meli_equivalence'     => 'MCO1276',
                            ],
                          '468240'                => [
                                'node'            => '0',
                                'name'            => 'Tools',
                                'meli_equivalence'     => 'MCO1953',
                            ],
                              '10272111'          => [
                                    'node'        => '0',
                                    'name'        => 'Tools',
                                    'meli_equivalence' => 'MCO1953',
                                ],
                            '165795011'           => [
                                  'node'          => '0',
                                  'name'          => 'Toys',
                                  'meli_equivalence'   => 'MCO1132',
                              ],
                              '165793011'         => [
                                    'node'        => '0',
                                    'name'        => 'Toys',
                                    'meli_equivalence' => 'MCO1132',
                                ],
                          '11846801'              => [
                                'node'            => '0',
                                'name'            => 'VideoGames',
                                'meli_equivalence'     => 'MCO1144',
                            ],
                            '2335753011'            => [
                                  'node'            => '0',
                                  'name'            => 'Wireless',
                                  'meli_equivalence'     => 'MCO1051',
                              ],
                              '2335752011'            => [
                                    'node'            => '0',
                                    'name'            => 'Wireless',
                                    'meli_equivalence'     => 'MCO1051',
                                ],
                            '1036592'             => [
                                'node'            => '0',
                                'name'            => 'Apparel & Accessories',
                                'meli_equivalence'     => 'MCO1132',
                            ],
                            '502394'              => [
                                'node'            => '0',
                                'name'            => 'Camera & Photo',
                                'meli_equivalence'     => 'MCO1039',
                            ],
                            '10963061'            => [
                                'node'            => '0',
                                'name'            => 'Car Toys',
                                'meli_equivalence'     => 'MCO1132',
                            ],
                            '468642'              => [
                                'node'            => '0',
                                'name'            => 'Computer & Video Games',
                                'meli_equivalence'     => 'MCO1144',
                            ],
                            '3367581'             => [
                                'node'            => '0',
                                'name'            => 'Jewelry',
                                'meli_equivalence'     => 'MCO3937',
                            ],
                            '284507'              => [
                                'node'            => '0',
                                'name'            => 'Kitchen & Housewares',
                                'meli_equivalence'     => 'MCO1574',
                            ],
                            '5174'                => [
                                'node'            => '0',
                                'name'            => 'Music',
                                'meli_equivalence'     => 'MCO1168',
                            ],
                            '11091801'            => [
                                'node'            => '0',
                                'name'            => 'Musical Instruments',
                                'meli_equivalence'     => 'MCO1182',
                            ],
                            '1064954'             => [
                                'node'            => '0',
                                'name'            => 'Office Products',
                                'meli_equivalence'     => 'MCO1499',
                            ],
                            '2619533011'          => [
                                'node'            => '0',
                                'name'            => 'Pet Supplies',
                                'meli_equivalence'     => 'MCO1071',
                            ],
                            '672123011'           => [
                                'node'            => '0',
                                'name'            => 'Shoes',
                                'meli_equivalence'     => 'MCO1430',
                            ],
                            '3375251'             => [
                                'node'            => '0',
                                'name'            => 'Sports & Outdoors',
                                'meli_equivalence'     => 'MCO1276',
                            ],
                            '228013'              => [
                                'node'            => '0',
                                'name'            => 'Tools & Hardware',
                                'meli_equivalence'     => 'MCO1648',
                            ],
          ],

];
